### ISSUE TITLE
solid-js dependency is not clear

### ISSUE THREAD

**Issue by brodybits** [ryansolid/react-solid-state#4]
I almost forgot: it was not clear to me that I have to add solid-js since it is a peer dependency. (Also not so clear to me why, though maybe the extra flexibility is good).

**Comment by ryansolid** [comment]
Yeah I don't see any reason why I didn't just make this a dependency. I will look at this as part of the update.

**Comment by ryansolid** [comment]
Yeah pushed in the latest release. Solid is now a dep. There is a peer dep of the JSX plugin now but it's unneeded here. It's likely I should split SolidDOM from Solid at some point.
