### ISSUE TITLE
how to solve the error .please help me

### ISSUE THREAD

**Issue by rajalingam771** [ryansolid/react-solid-state#5]
![Screenshot_1555501565](https://user-images.githubusercontent.com/37829531/56366538-01763180-6211-11e9-8d42-7d776b416bae.png)
![Screenshot_1555503928](https://user-images.githubusercontent.com/37829531/56366539-020ec800-6211-11e9-93c0-f6159055e58d.png)

**Comment by ryansolid** [comment]
I honestly have no idea what that is. It seems to be some issue with the native Java modules for Android. React Solid State is just a state library that works in the JavaScript runtime, and does not itself interact with the native side at all. Not to say there couldn't be some cascading effect but these errors alone point to somewhere that I can make no discernible connection between them and this library.

**Comment by rajalingam771** [comment]
Iam solved the error

**Comment by ryansolid** [comment]
Ok great to hear. I will close this issue now. Re-open if you feel there is a specific thing I can fix in this library.
